In [2]:
pip install numpy

[1 2 3 4 5]


In [1]:
import numpy as np

0-D Array

In [28]:
arr = np.array(42)
print(42)
arr.ndim

42


0

1-D Array : collection de 0-D array

In [29]:
arr1 = np.array([1,2,3,4,5])
print(arr1)
arr1.ndim

[1 2 3 4 5]


1

2-D Array : collection de 1-D array

In [30]:
arr2 = np.array([[1,2,3,],[4,5,6,]])
print(arr2)
arr2.ndim

[[1 2 3]
 [4 5 6]]


2

3-D array : collection de 2-D array

In [31]:
arr3 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr3)
arr3.ndim

[[1 2 3]
 [4 5 6]
 [7 8 9]]


2

3-D array with two 2-D array

In [32]:
arr4 = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(arr4)
arr4.ndim

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


3

4-D array

In [33]:
arr5 = np.array([[[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]],[[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]]])
print(arr5)
arr5.ndim

[[[[1 2 3]
   [4 5 6]]

  [[1 2 3]
   [4 5 6]]]


 [[[1 2 3]
   [4 5 6]]

  [[1 2 3]
   [4 5 6]]]]


4

In [34]:
print(arr1.shape)
print(arr2.shape)
print(arr3.shape)
print(arr4.shape)
print(arr5.shape)

(5,)
(2, 3)
(3, 3)
(2, 2, 3)
(2, 2, 2, 3)


In [36]:
new_arr = arr5.reshape(4,6)
new_arr

array([[1, 2, 3, 4, 5, 6],
       [1, 2, 3, 4, 5, 6],
       [1, 2, 3, 4, 5, 6],
       [1, 2, 3, 4, 5, 6]])

In [38]:
new_arr = arr3.reshape(1,3,3)
print(new_arr.ndim)
new_arr

3


array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [39]:
twoD_array = np.array([[1,2,3,4,5],[6,7,8,9,0]])
flattern_1D = twoD_array.reshape(-1)
flattern_1D

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0])

Indexing Numpy array

In [23]:
arr = np.array([2,3,4,5,6,7,8,9,0,1])
arr

array([2, 3, 4, 5, 6, 7, 8, 9, 0, 1])

In [4]:
arr.ndim

1

In [5]:
arr[0]

2

In [6]:
arr[2]+arr[1]

7

In [8]:
arr2 = np.array([[1,2,3,4,5],[6,7,8,9,0]])
arr2

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 0]])

In [9]:
# access element from 2nd row and 5th column

In [10]:
arr2[1,4]

0

In [11]:
for i in arr:
    print(i)

2
3
4
5
6


In [12]:
for j in arr2:
    print(j)

[1 2 3 4 5]
[6 7 8 9 0]


In [13]:
for ligne in arr2:
    for element in ligne:
        print(element)

1
2
3
4
5
6
7
8
9
0


In [16]:
arr[1:5]

array([3, 4, 5, 6])

In [19]:
arr[1::2]

array([3, 5])

In [21]:
# slice a 2D array
arr2[1,1:4]

array([7, 8, 9])

In [22]:
arr2

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 0]])

Searching Arrays

search an array for a certain value, and return the indexe that get a match. use the where() method

In [24]:
arr

array([2, 3, 4, 5, 6, 7, 8, 9, 0, 1])

In [27]:
x = np.where(arr==1)# return the index of the position of the element
x

(array([9]),)

In [28]:
impair = np.where(arr%2!=0)
impair

(array([1, 3, 5, 7, 9]),)

In [29]:
np.sort(arr)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])